### PR TITLE
add filename printing to non-watch runs

### PR DESCRIPTION
**Pull request by j-po**
addresses #179

### CODE REVIEW

**Comment by j-po** [comment]
- Sorry for not clearly marking this as WIP. tests are upcoming
- I generally try to avoid the indirection of tersely-named intermediary bindings like `f`, but I'll try to come up with something that meets both of our needs
- I was considering a solution inside of the file processing function, and I'm happy to revisit that

**Comment by aviflax** [comment]
No worries, sounds good!

**Comment by j-po** [comment]
one wrinkle in using the same codepath for both is that a lot of the logic in the existing printing logic for watch only really makes sense in that context.

**Comment by aviflax** [comment]
> one wrinkle in using the same codepath for both is that a lot of the logic in the existing printing logic for watch only really makes sense in that context.

Yeah, I thought that might be the case. I’ll take a look and see if I can think of something, but don’t let this slow you down; it’s hasn’t met the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) threshold for duplication so let’s not prematurely apply [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) — do what seems best to you.

**Comment by j-po** [comment]
debugging an issue where nothing prints in watch mode. I think for some reason `process-file` isn't being run

**Comment by aviflax** [comment]
This work has stalled as @j-po and I are no longer on the same team. I’m going to take it over, but I’m closing this PR for now and will probably open a new PR as a follow-up soon.

**Pull request closed without merging**
