### PR TITLE
sample function to process a file

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Just in case you think it might be useful @aviflax 
I guess it should probably live in a different namespace though since it's not really related with clipboards..

### CODE REVIEW

**Comment by aviflax** [comment]
Thanks!

I agree, it should go in a different namespace. Probably `fc4c.io`.

Also, I prefer PRs to be as focused as possible. So I’d prefer renaming functions in this namespace to be done in a separate PR from the one that adds such a function.

**Comment by AndreaCrotti** [comment]
It is related @aviflax, because without that change I would have to call `slurp` with `clojure.core/slurp` for example.
So if I move it to a different file then it's not related, but at the moment it was.

**Comment by sgerrand** [comment]
Somewhat of a tangent, but what's the idea behind `fc4c.io` as a namespace? Is there a link to the Indian Ocean that I've previously missed? Would `fc4c.org` make more sense? (💯 ❓s)

**Comment by aviflax** [comment]
@AndreaCrotti wrote:

> It is related @aviflax, because without that change I would have to call `slurp` with `clojure.core/slurp` for example.
So if I move it to a different file then it's not related, but at that moment it was.

True, true. I think I meant to address the scenario wherein the function is moved to a different namespace. In that case, I’d advocate for removing the other changes from the PR so it’s more focused.

----

@sgerrand wrote:

> Somewhat of a tangent, but what's the idea behind `fc4c.io` as a namespace? Is there a link to the Indian Ocean that I've previously missed? Would `fc4c.org` make more sense? (💯 ❓s)

In the Clojure community, it’s idiomatic to name namespaces after a domain, subdomain, domain concept, feature, or area of functionality ([Sierra, 2011](https://stuartsierra.com/2011/08/08/clojure-namespaces); [Hagleberg, 2010](https://groups.google.com/d/msg/clojure/lo6QZiI8Ois/mfmCeSG0K5EJ)). ([Reverse domain notation](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) is hardly ever used in Clojure projects.) In this case, `io` refers to I/O, Input/Output.

The idea here is to constrain non-pure functions to this one namespace, so as to keep them isolated from the rest of the pure functions. This is my attempt to respect the community’s general consensus that it’s best to keep side effects “at the edges” ([Corfield, 2017](https://coderanch.com/t/685451/paradigms/Functional-Programming-Java-put-Side#3217424)) so most of an app is easier to debug, understand, test, etc. This makes sense to me because pure and non-pure functions lend themselves to notably different approaches of testing and debugging.

**Comment by sgerrand** [comment]
> In this case, io refers to I/O, Input/Output.

Got it, thanks!

**Comment by aviflax** [comment]
@AndreaCrotti if you feel like moving this function to `fc4.io` and adding a test then I’d be inclined to accept this… up to you of course.

**Comment by AndreaCrotti** [comment]
I'm not sure it's worth tbh, I originally did this thinking that with fc4c I could simply generate the diagram directly, in which case I would have wanted a simple way to pass an input and get an output file.
Since it's not the case it probably doesn't help much to have that in..

**Comment by AndreaCrotti** [comment]
And about the focus of PRs @aviflax up to you, but I think in my experience being too strict about these kind of rules only harm the quality of the project overall, since if you expect others to create a separate PR for every small thing they think could be improved they simply won't do it.
(and this is particularly true whenever we have a more strict process like ST which means creating PRs alone is not enough)

I agree they should at least be done in separate commits though.

**Comment by aviflax** [comment]
> I'm not sure it's worth tbh, I originally did this thinking that with fc4c I could simply generate the diagram directly, in which case I would have wanted a simple way to pass an input and get an output file.

Aha, I see, yeah, that makes sense.

Apropos to that, I just posted a draft of [Enhancement Proposal EP02: Automated Rendering](https://github.com/FundingCircle/fc4-framework/pull/74) — if you have a few minutes I’d love your feedback on that, and/or on [its relative priority to other potential enhancements](https://github.com/FundingCircle/fc4-framework/issues/72).

> …I think in my experience being too strict about these kind of rules only harm the quality of the project overall, since if you expect others to create a separate PR for every small thing they think could be improved they simply won't do it.

Good food for thought, I’ll definitely consider this. Thank you!

**Pull request closed without merging**
