### PR TITLE
Update Clojure in builder image to v1.10

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Missed in #130.

### CODE REVIEW

**Comment by sgerrand** [comment]
> I think we should also update the base images of the Dockerfiles used for local testing and packaging

To what?

**Comment by aviflax** [comment]
> To what?

To this new build image hosted at Quay.

E.G.: https://github.com/FundingCircle/fc4-framework/blob/master/tool/Dockerfile.test#L6

The base image used by these local Dockerfiles for local use should match that used in CI.

Seems like it’d be a good idea to add a comment to that effect to the files.

**Comment by aviflax** [comment]
Aha, I see a97ec5f — excellent. That covers `Dockerfile.test` but we need to update `Dockerfile.pkg` as well.

**Comment by sgerrand** [comment]
> worth maybe squashing a few of the commits together as well?

Very much so. Done in 46d53116f29104021d7854bfa12c1d66cdad2aaf. ♻️

**Pull request merged**
